name: 522assignment2
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.3
  - pandas=2.3
  - scikit-learn=1.7
  - scipy=1.16
  - joblib=1.5
  - pip
  - setuptools
  - wheel
  - six
  - threadpoolctl
